# Generated by Django 3.2 on 2025-01-04 20:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0004_auto_20250104_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cpf',
            field=models.CharField(error_messages={'unique': 'Este CPF já está cadastrado.'}, max_length=14, unique=True, validators=[django.core.validators.RegexValidator(message='CPF deve estar no formato 999.999.999-99', regex='^\\d{3}\\.\\d{3}\\.\\d{3}-\\d{2}$')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(error_messages={'unique': 'Este telefone já está cadastrado.'}, max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message='Telefone deve estar no formato (99) 99999-9999', regex='^\\(\\d{2}\\) \\d{5}-\\d{4}$')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'Este nome de usuário já está em uso.'}, max_length=150, unique=True),
        ),
    ]
