# Generated by Django 4.2.10 on 2025-01-15 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0005_auto_20250104_2037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='cep',
        ),
        migrations.RemoveField(
            model_name='user',
            name='cpf',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone',
        ),
    ]
